### ISSUE TITLE
Implement Additional API Endpoints for Fetching and Serving Playlists, Albums, and Genres

### ISSUE THREAD

**Issue by JimNikou** [JimNikou/Loopify#23]
Extend the backend functionality by adding new API endpoints to retrieve and serve playlists, albums, and genres from the music database. These endpoints should be optimized for performance and scalability, providing structured data to the front-end. The new APIs will support filtering, sorting, and pagination to handle larger datasets effectively. This feature is essential for enhancing the app's browsing and discovery capabilities, allowing users to explore music collections more efficiently. Each endpoint should be fully documented for ease of integration with the front-end services.

**Comment by npetalid** [comment]
This is definitely an epic but it is too vague to be a good epic. For example "The endpoints should be optimized for performance and scalability". This is a wish and is not measurable by any means. How will you know that it has been completed? If you want to state performance goals try something along the lines of 'the app should server at least 1000 requests/minute' instead of just stating 'performance'. I would go on and mention specific resources that should be handled and specific functionality that is required by the current or at most next version of your product
